name: Enhanced-SlimeWorldManager
version: ${project.version}
main: com.grinderwolf.eswm.plugin.SWMPlugin
author: Grinderwolf
authors:
  - Grinderwolf
  - Gerolmed
  - andrei1058
description: Enhanced-SlimeWorldManager is a resource that implements the Slime Region Format, designed by the Hypixel Team to load and save worlds more efficiently.
api-version: '1.13'
commands:
  eswm:
    description: Main E-SWM command.
    usage: /eswm <cmd>
