name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download additional dependencies
      run: |
        wget https://cdn.getbukkit.org/spigot/spigot-1.15.1.jar && mvn install:install-file -Dfile=spigot-1.15.1.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.15.1-R0.1-SNAPSHOT -Dpackaging=jar
        wget https://cdn.getbukkit.org/spigot/spigot-1.14.4.jar && mvn install:install-file -Dfile=spigot-1.14.4.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.14.4-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O paper-1.13.2.jar https://yivesmirror.com/files/paper/Paper-1.13.2-b624.jar && mvn install:install-file -Dfile=paper-1.13.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.13.2-R0.1-SNAPSHOT -Dpackaging=jar
        wget https://cdn.getbukkit.org/spigot/spigot-1.13.jar && mvn install:install-file -Dfile=spigot-1.13.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.13-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O paper-1.12.2.jar https://yivesmirror.com/files/paper/Paper-1.12.2-b1618.jar && mvn install:install-file -Dfile=paper-1.12.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.12.2-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O paper-1.11.2.jar https://papermc.io/api/v1/paper/1.11.2/1104/download && mvn install:install-file -Dfile=paper-1.11.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.11.2-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O paper-1.10.2.jar https://papermc.io/ci/job/Paper/916/artifact/paperclip-916.2.jar && java -Dpaperclip.patchonly=true -jar paper-1.10.2.jar && mvn install:install-file -Dfile=cache/patched_1.10.2.jar -DgroupId=com.destroystokyo.paper -DartifactId=paper -Dversion=1.10.2-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O spigot-1.9.4.jar https://cdn.getbukkit.org/spigot/spigot-1.9.4-R0.1-SNAPSHOT-latest.jar && mvn install:install-file -Dfile=spigot-1.9.4.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.9.4-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O spigot-1.9.jar https://cdn.getbukkit.org/spigot/spigot-1.9-R0.1-SNAPSHOT-latest.jar && mvn install:install-file -Dfile=spigot-1.9.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.9-R0.1-SNAPSHOT -Dpackaging=jar
        wget -O spigot-1.8.8.jar https://cdn.getbukkit.org/spigot/spigot-1.8.8-R0.1-SNAPSHOT-latest.jar && mvn install:install-file -Dfile=spigot-1.8.8.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.8.8-R0.1-SNAPSHOT -Dpackaging=jar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
